### ISSUE TITLE
sfcapd segfault when -E

### ISSUE THREAD

**Issue by hamshiva** [phaag/nfdump#121]
I'm running the 1.6.17 version with enable-sflow option and it turns out that using the -E option on the CLI induce sfcapd to segfault.

Here is the gdb output:

```
Core was generated by `sfcapd -p 6343 -l /data//nfdump/ -E'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4a8614edcc in _IO_vfprintf_internal (s=s@entry=0x7ffc17ff0690, format=<optimized out>, 
    format@entry=0x7f4a868f8678 <error: Cannot access memory at address 0x7f4a868f8678>, ap=ap@entry=0x7ffc17ff07f8)
    at vfprintf.c:1642
1642	vfprintf.c: No such file or directory.
(gdb) where 
#0  0x00007f4a8614edcc in _IO_vfprintf_internal (s=s@entry=0x7ffc17ff0690, format=<optimized out>, 
    format@entry=0x7f4a868f8678 <error: Cannot access memory at address 0x7f4a868f8678>, ap=ap@entry=0x7ffc17ff07f8)
    at vfprintf.c:1642
#1  0x00007f4a86176409 in _IO_vsnprintf (
    string=0x7f4a86b06980 "\nFlow Record: \n  Flags        =", ' ' <repeats 14 times>, "0x80 FLOW, Sampled\n  label        =", ' ' <repeats 12 times>, "\200\275(\373\377\377\n  export sysid =", ' ' <repeats 17 times>, "1\n  size         =", ' ' <repeats 16 times>, "64\n  first        =        1527765"..., maxlen=<optimized out>, 
    format=0x7f4a868f8678 <error: Cannot access memory at address 0x7f4a868f8678>, args=args@entry=0x7ffc17ff07f8)
    at vsnprintf.c:119
#2  0x00007f4a86154e22 in __snprintf (s=<optimized out>, maxlen=<optimized out>, format=<optimized out>) at snprintf.c:33
#3  0x00007f4a868e1fc8 in ?? ()
#4  0x0000000000000050 in ?? ()
#5  0x0000000000000001 in ?? ()
#6  0x0000000000000040 in ?? ()
#7  0x000000005b0fdbba in ?? ()
#8  0x00007ffc17ff0a90 in ?? ()
#9  0x000000005b0fdbba in ?? ()
#10 0x00007ffc17ff0ad0 in ?? ()
#11 0x00000000000002ca in ?? ()
#12 0x00000000000002ca in ?? ()
#13 0x00007ffc17ff09d0 in ?? ()
#14 0x00007ffc17ff0a00 in ?? ()
#15 0x00007f4a868e1f38 in ?? ()
#16 0x00007f4a8614f99a in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=<optimized out>)
    at vfprintf.c:1641
#17 0x00000000004050ae in StoreSflowRecord (sample=sample@entry=0x7ffc17ff1120, fs=fs@entry=0xc6b050) at sflow_nfdump.c:674
#18 0x0000000000407f65 in readFlowSample (sample=sample@entry=0x7ffc17ff1120, expanded=expanded@entry=0, 
    fs=fs@entry=0xc6b050, verbose=verbose@entry=1) at sflow_process.c:3518
#19 0x00000000004092e8 in readSFlowDatagram (sample=0x7ffc17ff1120, fs=0xc6b050, verbose=1) at sflow_process.c:3581
---Type <return> to continue, or q <return> to quit--- 
#20 0x0000000000404469 in Process_sflow (in_buff=<optimized out>, in_buff_cnt=<optimized out>, fs=0xc6b050)
    at sflow_nfdump.c:226
#21 0x00000000004039e0 in run (receive_packet=<optimized out>, report_seq=<optimized out>, compress=<optimized out>, 
    time_extension=<optimized out>, use_subdirs=<optimized out>, t_begin=<optimized out>, twin=<optimized out>, peer=..., 
    socket=<optimized out>) at sfcapd.c:625
#22 main (argc=0, argv=0xc6b050) at sfcapd.c:1074
```

**Comment by phaag** [comment]
Would you mind to recompile the tools without optimisation ( -O2) and resend the gdb output. Segfault is unclear.

**Comment by hamshiva** [comment]
I juste recompiled the same source code using -O0 and it's not crashing anymore ...
