### ISSUE TITLE
aarch64: nfpcapd segfault after a few seconds

### ISSUE THREAD

**Issue by johnp789** [phaag/nfdump#278]
On a Raspberry Pi 4, 64-bit Arch Linux ARM, and `nfpcapd` built from master 78505418e, I'm seeing a segmentation fault after running a few seconds.  

```
$ uname -a
Linux pi4-e8d2e7ed 5.11.4-1-ARCH #1 SMP Sun Mar 7 23:46:10 UTC 2021 aarch64 GNU/Linux

$ sudo nfpcapd -i eth0 -l /tmp/flows/lan 2>&1 |less
Add extension: 2 byte input/output interface index
Add extension: 4 byte input/output interface index
Add extension: 2 byte src/dst AS number
Add extension: 4 byte src/dst AS number
Add extension: dst tos, direction, src/dst mask
Add extension: IPv4 next hop
Add extension: IPv6 next hop
Add extension: IPv4 BGP next IP
Add extension: IPv6 BGP next IP
Add extension: src/dst vlan id
Add extension: 4 byte output packets
Add extension: 8 byte output packets
Add extension: 4 byte output bytes
Add extension: 8 byte output bytes
Add extension: 4 byte aggregated flows
Add extension: 8 byte aggregated flows
Add extension: in src/out dst mac address
Add extension: in dst/out src mac address
Add extension: MPLS Labels
Add extension: IPv4 router IP addr
Add extension: IPv6 router IP addr
Add extension: router ID
Add extension: BGP adjacent prev/next AS
Add extension: time packet received
Add extension: NSEL Common block
Add extension: NSEL xlate ports
Add extension: NSEL xlate IPv4 addr
Add extension: NSEL xlate IPv6 addr
Add extension: NSEL ACL ingress/egress acl ID
Add extension: NSEL username
Add extension: NSEL max username
Add extension: nprobe/nfpcapd latency
Add extension: NEL Common block
Add extension: Compat NEL IPv4
Add extension: NAT Port Block Allocation
Startup.
[281473265582096] WaitDone() waiting
Unexpected empty FlowNode_ProcessList
[many repeats of above line]
Unexpected empty FlowNode_ProcessListSegmentation fault
```

Oddly, if I configure with `--enable-devel` and build, then `nfpcapd` seems to run OK.  It didn't segfault when running for several minutes.  It did however output this message upon interrupting the process with Ctrl-C: 
```
==9944==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 136 byte(s) in 1 object(s) allocated from:
    #0 0xffff9c21d52c in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0xaaaad9e1ba90 in NewNodeList /home/john/nfdump/bin/flowtree.c:419
    #2 0xaaaad9e11838 in main /home/john/nfdump/bin/nfpcapd.c:1602
    #3 0xffff9be61534 in __libc_start_main (/usr/lib/libc.so.6+0x24534)
    #4 0xaaaad9e121c0  (/usr/local/bin/nfpcapd+0x121c0)

SUMMARY: AddressSanitizer: 136 byte(s) leaked in 1 allocation(s).
```

**Comment by phaag** [comment]
Hmm .. strange - what hardware are you using?

**Comment by phaag** [comment]
Could you please test with the latest master branch?

**Comment by johnp789** [comment]
After making a fresh build with the problem commit and confirming that I could reproduce the segfault on my Pi 4, I built nfpcapd from commit 0ed38597d2b373d1b1402aa0efbfe0b9311335e2 and installed it.  I no longer saw a segfault, and it appears to capture and write output fine now.  Thanks!
